[package]
name = "Artificial-Culture-Rust-"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.16", features = ["asset_processor"] }
bincode = "2.0.1"
rust-analyzer = "0.0.1"
serde = "1.0.219"
sled = "0.34.7"
uuid = "1.17.0"