[build]
# This ensures dynamic linking is always used in dev builds
rustflags = ["-C", "prefer-dynamic"]

# Alternative: set target-specific flags
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "prefer-dynamic"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "prefer-dynamic"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "prefer-dynamic"]